
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: false,
    MOVIES_DATABASE_TOKEN: '08082f3821067996d5ba27ffe766a253'
  };
